r =(input("Please choose a car or a bike"))
if r=="car":
    print("You have chosen car")
    c =input("Please choose BMW or Hyndai")
    if c=="BMW":
        print("You have chosen a BMW")
    elif c=="Hyndai":
        print("You have chosen a Hyndai")
    else:
        print("Invalid option")
elif r=="bike":
    print("Ypu have chosen a bike")
    b =input("Please choose a Royalnfield or Honda civic")
    if b=="Royalnfield":
        print("You have chosen Royalnfield")
    elif  b=="Honda civic":
        print("You have chosen Honda civic")
    else:
        print("Invalid option")